#!/bin/bash

# Copy to /etc/cron.daily to run this.

# Upgrades google-chrome-stable in the background because it is slow. Named
# zzz-google-chrome-upgrade so it goes last and because it's slow...

# This will mark it for upgrade, pull the update, and upgrade the package.
apt --ignore-hold install google-chrome-stable
